#!/usr/bin/env node

const bytes = require('bytes')

const { argv } = require('yargs')
  .usage('Usage: ./$0 <source id> <target id> [options]\ntarget id optional, if not filled, use DEFAULT_TARGET in config.js')
  .alias('u', 'update')
  .describe('u', 'Do not use local cache, force to get source folder information from online' )
  .alias('f', 'file')
  .describe('f', 'Copy a single file')
  .alias('n', 'name')
  .describe('n', 'Rename the target folder, keep the original directory name if not filled in' )
  .alias('N', 'not_teamdrive')
  .describe('N', 'If it is not a team disk link, you can add this parameter to improve the interface query efficiency and reduce the delay')
  .alias('s', 'size')
  .describe('s', 'Do not fill in the default copy all files, if this value is set, then files smaller than this size will be filtered out, and must end with b, such as 10mb')
  .alias('S', 'service_account')
  .describe('S', 'Specify to use the service account for operation, provided that the json authorization file must be placed in the ./sa directory, please make sure that the sa account has operation permissions.')
  .alias('D', 'dncnr')
  .describe('D', 'Do not create new root,do not create a folder with the same name at the destination, directly copy the files in the source folder to the destination folder as they are')
  .help('h')
  .alias('h', 'help')

const { copy, copy_file, validate_fid } = require('./src/gd')
const { DEFAULT_TARGET } = require('./config')

let [source, target] = argv._

if (validate_fid(source)) {
  const { name, update, file, not_teamdrive, size, service_account, dncnr } = argv
  if (file) {
    target = target || DEFAULT_TARGET
    if (!validate_fid(target)) throw new Error('target id format is incorrect' )
    return copy_file(source, target, service_account).then(r => {
      const link = 'https://drive.google.com/drive/folders/' + target
      console.log('Task completed, file location：\n', link)
    }).catch(console.error)
  }
  let min_size
  if (size) {
    console.log(`Do not copy files smaller than ${size }`)
    min_size = bytes.parse(size)
  }
  copy({ source, target, name, min_size, update, not_teamdrive, service_account, dncnr }).then(folder => {
    if (!folder) return
    const link = 'https://drive.google.com/drive/folders/' + folder.id
    console.log('\ntask completed, new folder link：\n', link)
  })
} else {
  console.warn('missing or malformed list ID')
}
