#!/usr/bin/env node

const { argv } = require('yargs')
  .usage('Usage: ./$0 <source id> <target id> [options]')
  .alias('u', 'update')
  .describe('u', 'Do not use local cache, force to get source folder information from online')
  .alias('S', 'service_account')
  .describe('S', 'use service account for operation, provided that the sa authorization json file must be placed in the ./sa directory')
  .help('h')
  .alias('h', 'help')

const { dedupe, validate_fid } = require('./src/gd')

const [fid] = argv._
if (validate_fid(fid)) {
  const { update, service_account } = argv
  dedupe({ fid, update, service_account }).then(info => {
    if (!info) return
    const { file_count, folder_count } = info
    console.log('Task completed, the total number of deleted files:', file_count, 'Number of directories:', folder_count )
  })
} else {
  console.warn('missing or malformed list ID')
}
